// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "restoran/features/order/model"

	mock "github.com/stretchr/testify/mock"
)

// OrderServiceInterface is an autogenerated mock type for the OrderServiceInterface type
type OrderServiceInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *OrderServiceInterface) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: pagination
func (_m *OrderServiceInterface) GetAll(pagination model.Pagination) ([]model.OrderResponse, error) {
	ret := _m.Called(pagination)

	var r0 []model.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Pagination) ([]model.OrderResponse, error)); ok {
		return rf(pagination)
	}
	if rf, ok := ret.Get(0).(func(model.Pagination) []model.OrderResponse); ok {
		r0 = rf(pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Pagination) error); ok {
		r1 = rf(pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *OrderServiceInterface) GetByID(id int) (*model.OrderResponse, error) {
	ret := _m.Called(id)

	var r0 *model.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.OrderResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.OrderResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: newData, stringToken
func (_m *OrderServiceInterface) Insert(newData model.OrderInput, stringToken string) (*model.OrderResponse, error) {
	ret := _m.Called(newData, stringToken)

	var r0 *model.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(model.OrderInput, string) (*model.OrderResponse, error)); ok {
		return rf(newData, stringToken)
	}
	if rf, ok := ret.Get(0).(func(model.OrderInput, string) *model.OrderResponse); ok {
		r0 = rf(newData, stringToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(model.OrderInput, string) error); ok {
		r1 = rf(newData, stringToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderServiceInterface creates a new instance of OrderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderServiceInterface {
	mock := &OrderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
