name: Docker Image CI

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-restoran:latest
      -  
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CNAME }}
            docker rm ${{ secrets.CNAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/go-restoran
            docker run --name ${{ secrets.CNAME }} -p 8000:8000 -d -e DBHOST=${{secrets.DBHOST}} -e DBPORT=3306 -e DBUSER=${{secrets.DBUSER}} -e DBNAME=${{secrets.DBNAME}} -e DBPASS= -e SECRET=${{secrets.JWTSECRET}} -e SERVER=8000 -e CLOUDINARY_CLOUD_NAME=${{secrets.CDN_CLOUD_NAME}} -e CLOUDINARY_API_KEY=${{CDN_API_KEY}} -e CLOUDINARY_API_SECRET=${{CDN_API_SECRET}} -e CLOUDINARY_UPLOAD_FOLDER_NAME=${{CDN_FOLDER_NAME}} -e MIDTRANS_SERVER_KEY=${{MT_SERVER_KEY}} ${{ secrets.DOCKERHUB_USERNAME }}/go-restoran
